# Generated by Django 3.0.7 on 2020-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200625_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleheading',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='articleheading',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
