# Generated by Django 3.0.7 on 2020-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200626_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articleheading',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/images'),
        ),
    ]
