# Generated by Django 3.0.7 on 2020-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articlefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeedback',
            name='feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
