# Generated by Django 3.0.7 on 2020-06-30 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articleedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeedback',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
