# Generated by Django 3.0.7 on 2020-06-30 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_articlefeedback_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleedit',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
