# Generated by Django 3.0.7 on 2020-07-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_articlepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='searchtags',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
