# Generated by Django 3.0.7 on 2020-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_searchtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
