# Generated by Django 3.0.7 on 2020-07-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagedate_mainarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoYouKnow',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('DoYouKnow', models.TextField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HomepageDate')),
            ],
        ),
    ]
