# Generated by Django 3.0.7 on 2020-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doyouknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doyouknow',
            name='DoYouKnow',
            field=models.CharField(max_length=300),
        ),
    ]
