# Generated by Django 3.0.7 on 2020-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200705_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doyouknow',
            name='doYouKnow',
            field=models.CharField(max_length=1000),
        ),
    ]
