# Generated by Django 3.0.7 on 2020-07-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200705_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('today', models.CharField(max_length=1000)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HomepageDate')),
            ],
        ),
    ]
