# Generated by Django 3.0.7 on 2020-07-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_todaypicturearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoYouKnowItem',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('doYouKnowItem', models.CharField(max_length=1000)),
                ('homepageDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HomepageDate')),
            ],
        ),
        migrations.RenameModel(
            old_name='Today',
            new_name='TodayItem',
        ),
        migrations.RenameField(
            model_name='mainarticle',
            old_name='date',
            new_name='homepageDate',
        ),
        migrations.RenameField(
            model_name='todayitem',
            old_name='date',
            new_name='homepageDate',
        ),
        migrations.RenameField(
            model_name='todayitem',
            old_name='today',
            new_name='todayItem',
        ),
        migrations.RenameField(
            model_name='todaypicturearticle',
            old_name='date',
            new_name='homepageDate',
        ),
        migrations.RenameField(
            model_name='todaypicturearticle',
            old_name='article',
            new_name='pictureArticle',
        ),
        migrations.DeleteModel(
            name='DoYouKnow',
        ),
    ]
